### ISSUE TITLE
Use K8 service accounts and tokens

### ISSUE THREAD

**Issue by fmendezh** [gbif/stackable-spark#1]
Suggest changes in coordination with @muttcg to user K8 service account and authentication tokens. 
This must be applied and tested in pipelines and occurrence downloads.

**Comment by zaultooz** [comment]
I have created and tested a new service acc with token on the Occurrence Downloads spark process. It is changing out the config.yaml and other files with a singular config which contains the token and the cluster CA embedded. For future use, I have created a shell script for creating new config if needed.
